version: 1
disable_existing_loggers: True

formatters:
    simple:
        format: '%(asctime)s - %(filename)s - %(name)s - %(levelname)s - %(lineno)s - %(message)s'
        datefmt: '%Y-%m-%d %H:%M:%S'

handlers:
    console:
        class: logging.StreamHandler
        level: INFO
        formatter: simple
        stream: ext://sys.stdout

loggers:
    development:
        level: INFO
        handlers: [console]
        propagate: no

root:
    level: INFO
    handlers: [console]